version: "3.8"
services:
  tempfiles-backend:
    container_name: tempfiles-backend
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BACKEND_BASE_URL=http://localhost:5000
      - BACKEND_PORT=5000
      - JWT_SECRET=simplesecret
      - DB_HOST=tempfiles-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      - tempfiles-db
    volumes:
      - tempfiles-tmp:/tmp

  tempfiles-db:
    container_name: tempfiles-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - tempfiles-db:/var/lib/postgresql/data

volumes:
  tempfiles-db:
  tempfiles-tmp: