version: "3.8"
services:
  tempfiles-backend:
    container_name: tempfiles-backend
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BACKEND_PORT=5000
      - JWT_SECRET=simplesecret
      - DB_TYPE=sqlite
    volumes:
      - tempfiles-tmp:/tmp

volumes:
  tempfiles-tmp: