basePath: /
info:
  contact:
    email: dev@tmpf.me
    name: API Support
    url: https://tmpf.me/credit
  description: This is a Tempfiles server for file and text sharing.
  termsOfService: https://tmpf.me/terms/
  title: Tempfiles API
  version: "2.0"
paths: {}
swagger: "2.0"
